# Timing
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Husky
- ros_topic_name: "/husky/joint_states"
  gz_topic_name: "/model/husky/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/husky/odometry"
  gz_topic_name: "/model/husky/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/husky/imu"
  gz_topic_name: "/model/husky/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/husky/cmd_vel"
  gz_topic_name: "/model/husky/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# Husky Lidar
- ros_topic_name: "/husky/scan"
  gz_topic_name: "/model/husky/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/husky/scan/points"
  gz_topic_name: "/model/husky/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# Husky Camera
- ros_topic_name: "/husky/camera/image_raw"
  gz_topic_name: "/model/husky/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/husky/camera/camera_info"
  gz_topic_name: "/model/husky/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/husky/camera/depth/image"
  gz_topic_name: "/model/husky/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/husky/camera/depth/points"
  gz_topic_name: "/model/husky/camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# Parrot
- ros_topic_name: "/parrot/odometry"
  gz_topic_name: "/model/parrot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/parrot/imu"
  gz_topic_name: "/model/parrot/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/parrot/cmd_vel"
  gz_topic_name: "/model/parrot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# Parrot Camera
- ros_topic_name: "/parrot/camera/image_raw"
  gz_topic_name: "/model/parrot/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/parrot/camera/camera_info"
  gz_topic_name: "/model/parrot/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/parrot/camera/depth/image"
  gz_topic_name: "/model/parrot/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/parrot/camera/depth/points"
  gz_topic_name: "/model/parrot/camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
